# -*- coding: utf-8 -*-
"""ML_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WEEHKl2jkXeCNk_eRU86B3SMPGSRl0s

HARSHINI J
2025AC05202
"""

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)

import matplotlib.pyplot as plt
import seaborn as sns

"""## Dataset Description

The Dry Bean Dataset is a multiclass classification dataset obtained
from the UCI Machine Learning Repository.

The dataset contains geometric measurements of dry bean samples.

There are 16 numerical predictor variables:

- Area
- Perimeter
- MajorAxisLength
- MinorAxisLength
- AspectRatio
- Eccentricity
- ConvexArea
- EquivDiameter
- Extent
- Solidity
- roundness
- Compactness
- ShapeFactor1
- ShapeFactor2
- ShapeFactor3
- ShapeFactor4

The target variable is `Class`.

The target contains seven bean varieties:

- SEKER
- BARBUNYA
- BOMBAY
- CALI
- HOROZ
- DERMASON
- SIRA
"""

RANDOM_STATE = 42
TEST_SIZE = 0.20
TARGET = "Class"

DATA_PATH = "./data/Dry_Bean_Dataset.xlsx"

MODEL_DIR = "."
OUTPUT_DIR = "./outputs"

TEST_DATA_PATH = "./test_data.csv"

os.makedirs(OUTPUT_DIR, exist_ok=True)
# Load the original UCI Dry Bean dataset

df = pd.read_excel(DATA_PATH)

print("Dataset loaded successfully.")
print("Dataset shape:", df.shape)
print("First five rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("Number of instances:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Number of features:", df.shape[1] - 1)
print("Number of classes:", df[TARGET].nunique())

print("\nTarget classes:")
print(sorted(df[TARGET].unique()))

missing_values = df.isnull().sum()

print("Missing values by column:")
display(missing_values)

print("\nTotal missing values:", missing_values.sum())
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)
if duplicate_count > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("Duplicates removed.")
else:
    print("No duplicate rows found.")

print("Dataset shape after duplicate handling:", df.shape)
class_counts = df[TARGET].value_counts()

print("Class distribution:")
display(class_counts)

plt.figure(figsize=(10, 5))

sns.countplot(
    data=df,
    x=TARGET,
    order=df[TARGET].value_counts().index
)

plt.title("Dry Bean Class Distribution")
plt.xlabel("Bean Class")
plt.ylabel("Number of Samples")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

X = df.drop(columns=[TARGET])
y = df[TARGET]

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())
non_numeric_columns = X.select_dtypes(
    exclude=["number"]
).columns.tolist()

if len(non_numeric_columns) == 0:
    print("All 16 predictor variables are numerical.")
else:
    print("Non-numeric columns found:")
    print(non_numeric_columns)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

print("\nTraining feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)

"""## Preprocessing Strategy

The dataset contains only numerical predictor variables, so no
categorical encoding is required.

The following preprocessing strategy is used:

1. The target variable `Class` is separated from the predictors.
2. The dataset is divided into 80% training and 20% testing data.
3. Stratified sampling is used to preserve the class distribution.
4. StandardScaler is applied to Logistic Regression, KNN, and
   Gaussian Naive Bayes.
5. Decision Tree and Random Forest are trained without scaling
   because tree-based algorithms are not sensitive to feature scale.
6. Scaling is performed inside a Pipeline so that the scaler is
   fitted only on the training data, preventing data leakage.
"""

test_data = X_test.copy()

test_data[TARGET] = y_test.values

test_data.to_csv(
    TEST_DATA_PATH,
    index=False
)

print("Test data saved successfully.")
print("Location:", TEST_DATA_PATH)
print("Shape:", test_data.shape)

display(test_data.head())

models = {

    "Logistic Regression": Pipeline([
        (
            "scaler",
            StandardScaler()
        ),
        (
            "model",
            LogisticRegression(
                max_iter=2000,
                random_state=RANDOM_STATE
            )
        )
    ]),

    "Decision Tree": Pipeline([
        (
            "model",
            DecisionTreeClassifier(
                random_state=RANDOM_STATE
            )
        )
    ]),

    "KNN": Pipeline([
        (
            "scaler",
            StandardScaler()
        ),
        (
            "model",
            KNeighborsClassifier(
                n_neighbors=5
            )
        )
    ]),

    "Naive Bayes": Pipeline([
        (
            "scaler",
            StandardScaler()
        ),
        (
            "model",
            GaussianNB()
        )
    ]),

    "Random Forest": Pipeline([
        (
            "model",
            RandomForestClassifier(
                n_estimators=100,
                random_state=RANDOM_STATE,
                n_jobs=-1
            )
        )
    ])
}

print("Five classification models defined:")
for name in models:
    print("-", name)

trained_models = {}

for model_name, model in models.items():

    print(f"\nTraining {model_name}...")

    model.fit(
        X_train,
        y_train
    )

    trained_models[model_name] = model

    print(f"{model_name} training completed.")

print("\nAll models trained successfully.")

results = {}

predictions = {}

probabilities = {}

for model_name, model in trained_models.items():

    # Predictions
    y_pred = model.predict(X_test)

    # Class probabilities
    y_proba = model.predict_proba(X_test)

    # Metrics
    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    auc = roc_auc_score(
        y_test,
        y_proba,
        multi_class="ovr",
        average="weighted"
    )

    precision = precision_score(
        y_test,
        y_pred,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred,
        average="weighted",
        zero_division=0
    )

    mcc = matthews_corrcoef(
        y_test,
        y_pred
    )

    results[model_name] = {
        "Accuracy": accuracy,
        "AUC": auc,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "MCC": mcc
    }

    predictions[model_name] = y_pred
    probabilities[model_name] = y_proba

results_df = pd.DataFrame(
    results
).T.reset_index()

results_df = results_df.rename(
    columns={"index": "ML Model Name"}
)

metric_columns = [
    "Accuracy",
    "AUC",
    "Precision",
    "Recall",
    "F1",
    "MCC"
]

results_display = results_df.copy()

results_display[
    metric_columns
] = results_display[
    metric_columns
].round(4)

display(results_display)
results_df.to_csv(
    "./outputs/model_comparison.csv",
    index=False
)

print("Model comparison saved to:")
print("./outputs/model_comparison.csv")

model_file_names = {
    "Logistic Regression": "logistic_regression.pkl",
    "Decision Tree": "decision_tree.pkl",
    "KNN": "knn.pkl",
    "Naive Bayes": "naive_bayes.pkl",
    "Random Forest": "random_forest.pkl"
}

for model_name, file_name in model_file_names.items():

    file_path = os.path.join(
        MODEL_DIR,
        file_name
    )

    joblib.dump(
        trained_models[model_name],
        file_path
    )

    print(
        f"Saved: {file_path}"
    )

class_names = sorted(
    y_test.unique()
)

for model_name, y_pred in predictions.items():

    cm = confusion_matrix(
        y_test,
        y_pred,
        labels=class_names
    )

    plt.figure(figsize=(8, 6))

    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        xticklabels=class_names,
        yticklabels=class_names
    )

    plt.title(
        f"Confusion Matrix - {model_name}"
    )

    plt.xlabel("Predicted Class")
    plt.ylabel("Actual Class")

    plt.tight_layout()
    plt.show()

for model_name, y_pred in predictions.items():

    print("\n" + "=" * 70)
    print(model_name)
    print("=" * 70)

    print(
        classification_report(
            y_test,
            y_pred,
            zero_division=0
        )
    )

winner_row = results_df.loc[
    results_df["F1"].idxmax()
]

print("Overall Best Model Based on F1 Score")
print("-" * 40)

print(
    "Model:",
    winner_row["ML Model Name"]
)

print(
    "Accuracy:",
    f"{winner_row['Accuracy']:.4f}"
)

print(
    "AUC:",
    f"{winner_row['AUC']:.4f}"
)

print(
    "Precision:",
    f"{winner_row['Precision']:.4f}"
)

print(
    "Recall:",
    f"{winner_row['Recall']:.4f}"
)

print(
    "F1:",
    f"{winner_row['F1']:.4f}"
)

print(
    "MCC:",
    f"{winner_row['MCC']:.4f}"
)